### ISSUE TITLE
crash report on WifiController.checkEduroamAnon

### ISSUE THREAD

**Issue by GarethAyres** [GEANT/CAT-Android#2]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in uk.ac.swansea.eduroamcat.WifiStatus@81111d3
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:893)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5458)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
    at uk.ac.swansea.eduroamcat.WifiController.checkEduroamAnon(WifiController.java:466)
    at uk.ac.swansea.eduroamcat.ConnectFragment.showCurrentState(ConnectFragment.java:115)
    at uk.ac.swansea.eduroamcat.ConnectFragment.setStatus(ConnectFragment.java:61)
    at uk.ac.swansea.eduroamcat.WifiStatus.onReceive(WifiStatus.java:89)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:883)
    ... 7 more

**Comment by GarethAyres** [comment]
Fixed with https://github.com/GEANT/CAT-Android/commit/f6a9f28714989587c8679cf9df57d52bb3dbb627

Gareth
