### ISSUE TITLE
null pointer crash for WifiController.checkSSID

### ISSUE THREAD

**Issue by GarethAyres** [GEANT/CAT-Android#3]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
    at uk.ac.swansea.eduroamcat.WifiController.checkSSID(WifiController.java:335)
    at uk.ac.swansea.eduroamcat.ConnectFragment.clickConnect(ConnectFragment.java:629)
    at uk.ac.swansea.eduroamcat.ConnectFragment.onClick(ConnectFragment.java:639)
    at android.view.View.performClick(View.java:5218)
    at android.view.View$PerformClick.run(View.java:20968)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6075)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by GarethAyres** [comment]
Fix for null list:  https://github.com/GEANT/CAT-Android/commit/e93d5909e84aaeccb78c6d0396642ffebc55b2a2

Gareth
