### ISSUE TITLE
non managed IDP TLS profile crashes app

### ISSUE THREAD

**Issue by GarethAyres** [GEANT/CAT-Android#30]
A TLS profile from CAT, that is not a full TLS profile crashes the app.

error:
2019-01-16 10:29:21.589 14658-14658/uk.ac.swansea.eduroamcat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.ac.swansea.eduroamcat, PID: 14658
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at uk.ac.swansea.eduroamcat.WifiConfigAPI18.saveEapConfig(WifiConfigAPI18.java:240)
        at uk.ac.swansea.eduroamcat.ConnectFragment.clickConnect(ConnectFragment.java:599)
        at uk.ac.swansea.eduroamcat.ConnectFragment.onClick(ConnectFragment.java:686)

**Comment by GarethAyres** [comment]
Fix pushed to github with null condition check on username for profiles missing a private key, but installing a partial tls profile.
