### ISSUE TITLE
Null pointer crash on WifiController.checkEduroamSSID

### ISSUE THREAD

**Issue by GarethAyres** [GEANT/CAT-Android#4]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
    at uk.ac.swansea.eduroamcat.WifiController.checkEduroamSSID(WifiController.java:446)
    at uk.ac.swansea.eduroamcat.ConnectFragment.showCurrentState(ConnectFragment.java:110)
    at uk.ac.swansea.eduroamcat.ConnectFragment.setStatus(ConnectFragment.java:61)
    at uk.ac.swansea.eduroamcat.ConnectFragment.clickConnect(ConnectFragment.java:556)
    at uk.ac.swansea.eduroamcat.ConnectFragment.onClick(ConnectFragment.java:639)
    at android.view.View.performClick(View.java:5207)
    at android.view.View$PerformClick.run(View.java:21168)
    at android.os.Handler.handleCallback(Handler.java:746)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5491)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by GarethAyres** [comment]
Fixed with https://github.com/GEANT/CAT-Android/commit/c5e5fb58952e48ca14355c87ef520824de428b24

Gareth
